import { chromium } from 'playwright';
import { createServer } from 'vite';
const server = await createServer({ server: { port: 0, host: '127.0.0.1' }, logLevel: 'error', root: '/home/user/Random-claude-session' });
await server.listen();
const url = `http://127.0.0.1:${server.httpServer.address().port}/?harness=1&quality=low`;
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist', '--use-gl=angle'] });
const page = await browser.newPage({ viewport: { width: 320, height: 200 } });
page.setDefaultTimeout(300000);
page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') console.log(m.type(), m.text().slice(0, 300)); });
await page.goto(url);
await page.waitForFunction(() => window.__genesis !== undefined);
await page.evaluate(() => window.__genesis.ready);
console.log(await page.evaluate(() => window.__genesis.groundCheck()));
await browser.close(); await server.close();
